pdf/pdf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from superadmin.views import*


urlpatterns = [
    
    path('login/', login_page, name='login'),
    path('', login_page),

    path('forget_password/', forget_password, name='forget_password'),
    path('forget_password_send_email/', forget_password_send_email, name='forget_password_send_email'),
    path('forget_password_send_email_check/<uid>/', forget_password_send_email_check,
        name='forget_password_send_email_check'),
    path('update_password/', update_password, name='update_password'),

    path('register/', register_page, name='register_page'),
    path('logout/', logout_page, name='logout'),

    path('adminn/', admin.site.urls),
    path('admin/',  include(('superadmin.urls', 'superadmin'), namespace='superadmin')),
    path('', include(('user.urls', 'user'), namespace='user')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pdf/user/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *


urlpatterns = [
  
     path('index/', index, name='index'),
     path('dashboard/', get_index_page, name='dashboard'),
     path('upload_file/', upload_file, name='upload_file'),
     path('upload_file/<str:service>/', upload_file, name='upload_file'),
     path('perform_services/', perform_services, name='perform_services'),
     path('download_docx/', download_docx, name='download_docx'),

     
]

pdf/user/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class MyModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    pdf = models.FileField(upload_to='pdf_input')
class Pdf(models.Model):
    pdf = models.FileField(upload_to='pdf_input')

class Storefile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    pdf = models.FileField(upload_to='pdf_input')
    

pdf/user/views.py
from django.http import Http404, HttpResponse
from django.shortcuts import render
from rest_framework.decorators import api_view
from rest_framework.views import APIView
from .serializers import PdfSerializer, StorefileSerializer
from rest_framework.response import Response
from rest_framework import status
from .models import Pdf, Storefile
from django.contrib.auth.decorators import login_required
from django.http import FileResponse
from .services.Expert_resourse import expert_resource_converter
from .services.Joss_Search import joss_converter
from .services.Aspion import aspion_converter
from .services.Clarus import clarus_converter
from .services.EdEx import edex_converter
from .services.Sang_Zarrin import sang_zarrin_converter
from .services.FMCG import fmcg_converter
from .services.linum import linum_converter
from .services.Alxander import alexander_steele_converter
from django.http import FileResponse
from django.conf import settings
from superadmin.models import Service, Myservice, Mypermission
import os
import time
import pdb

# Create your views here.
@login_required
def get_index_page(request):
    mypermissions = Mypermission.objects.filter(user=request.user)
    myservices = Myservice.objects.filter(mypermission__user=request.user,is_permisstion=True)

 
    if request.user.is_superuser:
        services_ = Myservice.objects.all()
        return render(request, 'superadmin/index.html',context={'service': services_})
    

    return render(request, 'user/index.html',context={'service': myservices})

@api_view(['GET'])
def index(request):
    file=Pdf.objects.get(id=5)
    return render(request, 'user/index.html', context={"file":file})

@api_view(['GET'])
@login_required
def upload_file(request ,service):
    return render(request, 'user/upload_file.html', context={"service_name":service})
    

@login_required
@api_view(['POST'])
def perform_services(request): 

    data=request.data
    serializer=StorefileSerializer(data=request.data)
    title = request.POST['title']
   
    
 
    if serializer.is_valid():
        serializer.save()
       
        obj=Storefile.objects.filter(user=request.user.id).last()
        path=str(obj.pdf)
        file_path = os.path.join(settings.MEDIA_ROOT, path)
        #/Users/manzoorhussain/Documents/Services/IlovePDF/pdf/media/pdf_output/Expert_Resource.docx
        #ouput_file = "pdf_output/Expert_Resource.docx"
        userfile= str(request.user.id)
        concatenated_str = userfile+"Common_Resource.docx"
        save_path = "pdf_input/"+concatenated_str
        save_path =  os.path.join(settings.MEDIA_ROOT, save_path)
        #file_path_output = os.path.join(settings.MEDIA_ROOT, ouput_file)
      
       
        if title:
            service_name = ("_".join(title.split())+"_Converter").lower()
            output_ = ("pdf_output/"+"_".join(title.split())+"_template.docx").lower()
            file_path_output = os.path.join(settings.MEDIA_ROOT, output_)
            (eval(service_name)(file_path,file_path_output,save_path))
            
        
        return Response(status=200, data=serializer.data)
    return Response(status=400,data=serializer.errors)
 
  
  

api_view(['GET'])
@login_required
def download_docx(request):
   
    
    obj = Storefile.objects.filter(user=request.user.id).last()
    if obj:
        
        id = obj.id
        input_file = str(obj.pdf) 
        input_file_path = os.path.join(settings.MEDIA_ROOT, input_file)
        file_name = "/pdf_input/"
        userfile= str(request.user.id);
        concatenated_str = userfile+"Common_Resource.docx"
        output = "pdf_input/"+concatenated_str
        #output = "pdf_input/Common_Resource.docx"
        file_path = os.path.join(settings.MEDIA_ROOT, output)
        #"/Users/manzoorhussain/Documents/Services/IlovePDF/pdf/media/pdf_input/output_expert_resource.docx"
        filename = os.path.basename(file_path)
        response = HttpResponse(content_type='application/octet-stream')
        response['Content-Disposition'] = f'attachment; filename="{filename}"'
        # Open the file and write its contents to the response
        with open(file_path, 'rb') as file:
            response.write(file.read())
        
            os.remove(input_file_path)
            os.remove(file_path)
            obj.delete()
        
        
        
            return response
        raise Http404
    response=400
    return response













   

pdf/user/templates/user/index.html
{% extends 'user/layout/base.html' %}

{% block content %}

      
        <div class="container" >
            <a href="" class="btn btn-primary" style="visibility: hidden;">dd</a>
        </div> 

      
        <div class="main__container">
         
            <div class="" style="display: flex;     flex-wrap: wrap;">
               {% for obj in service %}
                <div class="card mycard">
                
                  <div class="card-body" >
                     
                   <a href="{% url 'user:upload_file' %}{{ obj.title }}/"> <h5 class="card-title">{{ obj.title }}</h5></a>
                    <p class="card-text">{{ obj.description}}</p>
                    <p class="card-text"><small class="text-muted"></small></p>
                  </div>
                </div>
                {% endfor %}
              
              </div>
                 
          </div>
        

{% endblock %}

{% block javascript %}
<script type="text/javascript">



</script>


{% endblock %}

pdf/user/templates/user/upload_file.html
{% extends 'user/layout/base.html' %}

{% block style %}

.custom-file-input::-webkit-file-upload-button {
    visibility: hidden;
  }
  
  .custom-file-input::before {
    content: 'Choose file';
    display: inline-block;
    background: #007bff;
    color: #fff;
    border-radius: 4px;
    padding: 8px 20px;
    outline: none;
    white-space: nowrap;
    -webkit-user-select: none;
    cursor: pointer;
    font-weight: 400;
    font-size: 1rem;
    line-height: 1.5;
    border-color: #007bff;
  }
  
  .custom-file-input:hover::before {
    border-color: #0069d9;
    background-color: #0069d9;
    color: #fff;
  }
  
  .custom-file-input:active::before {
    background-color: #0062cc;
    border-color: #005cbf;
  }

 .upload_button{

    color: #fff;
    background-color: #dc3545;
    border-color: #dc3545;
    padding: 12PX 96PX;
  }
  
    .loader-container {
        display: none;
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        z-index: 9999;
    }
    .loader {
        border: 4px solid #f3f3f3;
        border-top: 4px solid #3498db;
        border-radius: 50%;
        width: 30px;
        height: 30px;
        animation: spin 2s linear infinite;
        margin: 0 auto;
    }
    .loader-text {
        margin-top: 10px;
        text-align: center;
    }
    @keyframes spin {
        0% { transform: rotate(0deg); }
        100% { transform: rotate(360deg); }
    }






{% endblock %}


{% block content %}
   
    <div class="container">
       
        <div class="row">
      
        
          
          <div class="col-3">

           
             
           
          </div>
          <div class="col-5" style="text-align: center;">
           
            <h1>Convert to {{ service_name }}</h1>
            <p>Format your unformatted Resume by using our AI powered solution with incredible accuracy.
                Developed by Machine learning 1.</p>

                <div class=""  style="display:none" id="download_button">
                    <a href="javascript:downloadFile();" class="btn btn-danger" style="padding: 12PX 74PX;
                    font-size: 20px;
                    text-align: center;">Download</a>
                   
                  
                  </div>
                <form method="POST" action="" enctype="multipart/form-data" id="upload_form">
                    {% csrf_token %} 
                    <div class="" id="select_button">
                        <label class="upload_button" for="fileInput"  style="
                        color: #fff;
                        background-color: #dc3545;
                        border-color: #dc3545;
                        padding: 12PX 74PX;
                        font-size: 20px;
                        text-align: center;">Select Word File</label>
                      
                      </div>
                    
                      <input type="hidden" name="title" id="title" value=" {{ service_name }}">
                      <input type="hidden" name="user" id="user" value=" {{ request.user.id }}">
                    <div>
                        <input type="file" class="form-control" name="pdf" id="fileInput" accept=".docx" style="display:none">
                    </div>  
                   
                    
                       

                      
          
                </form>
                <div class="loader-container" id="loader_container">
                  <div class="loader"></div>
                  <div class="loader-text"></div>
                  <br>
              </div>
              <div class="loader-text" id="loader-text" style="display: none;">Taking time for getting response from api</div>
              <div id="mybar_main" style="display:none;">
               
                <div id="myBar"></div>
              </div>
             
                
                <div class=""  style="display:none" id="convert_button" >
                    <label class="upload_button"  style="
                    color: #fff;
                    background-color: #dc3545;
                    border-color: #dc3545;
                    padding: 12PX 74PX;
                    font-size: 20px;
                    text-align: center;">Click to Convert</label>
                  
                  </div>
                 
          </div>
        
          <div class="col-3">
          
            
           
          </div>
         

         
        </div>
      </div>
     

{% endblock %}

{% block javascript %}

<script>
    $(function() {
        // Handle file selection event
        $('#fileInput').on('change', function() {
          // Get selected file name
        var fileName = $(this).val().split('\\').pop();
          // Update label text
        $(this).next('.input-group-text').html(fileName);
        $('#fileInput').css('display', 'block')
        $('#select_button').css('display','none')
        $('#convert_button').css('display','block')


        //# previewFile()
       
         

        });
    });
  
    
 
   
    const convert_button = document.getElementById("convert_button");

    convert_button.addEventListener("click", function() {
              
                //runProgressBar(120);

         
           
            $('#mybar_main').css('display','block')
            $('#loader-text').css('display','block')
          
            $('#fileInput').css('display', 'none')
            $('#select_button').css('display','none')
            $('#convert_button').css('display','none')

            
            var myform = document.getElementById("upload_form");
            var fd = new FormData(myform);
            var i = 0;
            move(i)

            $.ajax({
                url: "/perform_services/",
                headers: {"X-CSRFToken": '{{csrf_token}}'},
                data: fd,
                cache: false,
                processData: false,
                contentType: false,
                type: 'POST',

             
                success: function (dataofconfirm) {
                   move(99)
                    $('#fileInput').css('display', 'none')
                    $('#select_button').css('display','none')
                    $('#convert_button').css('display','none')
                    
                    $('#loader_container').css('display','none')
                    $('#mybar_main').css('display','none')
                    $('#loader-text').css('display','none')
                    $('#download_button').css('display','block')
                    
                    //window.location.reload()
                  
                },
                error: function (data) {
                    //document.getElementById('save').innerHTML = '';
                    ShowNotify('Error', data.responseJSON.error, 'error');
                }
            });
    });
   
    function move(i) {
      if (i == 0) {
        i = 1;
        var elem = document.getElementById("myBar");
        var width = 1;
        var id = setInterval(frame, 1800);
        function frame() {
          if (width >= 100) {
            clearInterval(id);
            i = 0;
          } else {
            width++;
            elem.style.width = width + "%";
          }
        }
      }
    }


    function downloadFile() {
        $.ajax({
          url: '/download_docx/',
          type: 'GET',
          xhrFields: {
          responseType: 'blob'
          },
          success: function(response) {
            const url = window.URL.createObjectURL(response);
            const link = document.createElement('a');
            link.href = url;
            var title = $('#title').val();
            title=title.replaceAll(" ","-");
            title='output'+title+'.docx'
            link.download =title
    
           

            // if (title.includes("Expert")) {
            //  link.download = 'output_expert_resource.docx';
            // }
            // if (title.includes("Joss")) {
            //   link.download = 'output_joss_search.docx';
            // }
            // if (title.includes("ASPION")) {
            //   link.download = 'output_aspion_search.docx';
            // }
            // if (title.includes("Clarus")) {
            //   link.download = 'output_clarus.docx';
            // }
            
            link.click();
            window.URL.revokeObjectURL(url);
            $('#select_button').css('display','block');
            $('#download_button').css('display','none');
          },
          error: function(xhr, status, error) {
            console.log("error");
          }
        });
      }


// Call the runProgressBar function with a duration of 3 minutes (180 seconds)




  
    {% comment %} 
    function downloadFile() {
        $.ajax({
            url: '/download_docx/',
            type: 'GET',
            success: function(response) {
                const blob = new Blob([response]);

                // create a temporary URL for the blob object
                const url = window.URL.createObjectURL(blob);
    
                // create a link element and set its properties
                const link = document.createElement('a');
                link.href = url;
                link.download = 'output_expert_resource.docx';
    
                // simulate a click on the link element
                link.click();
    
                // clean up the temporary URL
                window.URL.revokeObjectURL(url);
                $('#select_button').css('display','block')
                $('#download_button').css('display','none')
        

            },
            error: function(xhr, status, error) {
                // handle error response
                console.log("error")
            }
        });
    } {% endcomment %}

      


        function previewFile() {
    
            const preview = document.getElementById('preview');
            const file = document.querySelector('input[type=file]').files[0];
            const reader = new FileReader();
        
            reader.addEventListener("load", function () {
              const pdfViewer = `<embed src="${reader.result}" width="500" height="600" type="application/docx">`;
              preview.innerHTML = pdfViewer;
            }, false);
        
            if (file) {
              reader.readAsDataURL(file);
            }
          }
        
        //  document.querySelector('input[type=file]').addEventListener('change', previewFile);
       


        

  
  
  
  
  
  

      

</script>
{% endblock %}