pdf/pdf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from superadmin.views import*


urlpatterns = [
    
    path('login/', login_page, name='login'),
    path('', login_page),

    path('forget_password/', forget_password, name='forget_password'),
    path('forget_password_send_email/', forget_password_send_email, name='forget_password_send_email'),
    path('forget_password_send_email_check/<uid>/', forget_password_send_email_check,
        name='forget_password_send_email_check'),
    path('update_password/', update_password, name='update_password'),

    path('register/', register_page, name='register_page'),
    path('logout/', logout_page, name='logout'),

    path('adminn/', admin.site.urls),
    path('admin/',  include(('superadmin.urls', 'superadmin'), namespace='superadmin')),
    path('', include(('user.urls', 'user'), namespace='user')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pdf/superadmin/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *


urlpatterns = [
    path('dashboard/', get_index_page, name='dashboard'),
    path('delete-service/', delete_service, name='delete_service'),
    path('change_service/', change_service, name='change_bank'),
    path('get_service_detail/', get_service_detail, name='get_service_detail'),
    path('add-service/', add_service, name='add_service'),

    path('get_user_detail/', get_user_detail, name='get_user_detail'),

    path('get-user-services/', get_user_services, name='get_user_services'),
    path('change-permission/', change_permission, name='change_permission'),
    
    


    
]

pdf/superadmin/models.py
from django.db import models 
from django.contrib.auth.models import User


# Create your models here.
class Service(models.Model):
    user = models.ManyToManyField(User)
    title = models.CharField(max_length=100, null=False, blank=False)
    description = models.TextField(max_length=1000, null=False, blank=False)
    is_permisstion = models.BooleanField(default=False)

class Permission(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    is_check = models.BooleanField(default=True)
class Myservice(models.Model):
    user = models.ManyToManyField(User)
    title = models.CharField(max_length=100, null=False, blank=False)
    description = models.TextField(max_length=1000, null=False, blank=False)
    is_permisstion = models.BooleanField(default=False)
class Mypermission(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    service = models.ForeignKey(Myservice, on_delete=models.CASCADE)
    is_check = models.BooleanField(default=True)

  
    
  

pdf/superadmin/views.py
from base64 import urlsafe_b64decode, urlsafe_b64encode
from email.message import EmailMessage
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from rest_framework.decorators import api_view
from rest_framework.response import Response
from django.contrib.auth.models import User
from django.contrib.auth.hashers import check_password
from django.middleware.csrf import get_token
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from .models import Service, Permission, Myservice, Mypermission
from .serializer import ServiceSerializer, PermisstionSerializer
from django.core import serializers

import pdb




# Create your views here.
@login_required
def get_index_page(request):
    services_ = Myservice.objects.all()
    print(services_,"hussain")

    if request.user.is_superuser:
       
        services_ = Myservice.objects.all()
        return render(request, 'superadmin/index.html',context={'service': services_})
    return redirect('user:dashboard')
 
    return render(request, 'user/index.html',context={'service': services_})
@api_view(['POST','GET'])
def login_page(request):
    if request.method == 'GET':
        user_ = request.user
        if user_.username:
            response = redirect('user:dashboard')
            return response
        else:
            error_message = ''
            return render(request, 'superadmin/auth/login.html', {'error_message': error_message})
        
   
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user_ = authenticate(username=username, password=password)
        
       
      
        if user_:
            login(request, user_)
           

            if user_.is_superuser:
                response = redirect('superadmin:dashboard')
            else:
                response = redirect('user:dashboard')
            response.set_cookie(key='name', value=user_.email)
            response.set_cookie(key='email', value=user_.username)
            
            return response
        else:
            error_message = 'Invalid username or password'
            return render(request, 'superadmin/auth/login.html', {'error_message': error_message})

        #response = render(request, 'superadmin/auth/login.html',context={"errors":"husain"})
        #return response

@api_view(['POST','GET'])
def register_page(request):
    if request.method == 'GET':
        user_ = request.user
        if user_.username:
            response = redirect('user:dashboard')
            return response
        else:
            return render(request, 'superadmin/auth/register.html')
        
    

    if request.method == 'POST':
        name_ = request.POST['full_name']
        email = request.POST['email'].lower().strip()
        password = request.POST['password']
      

        if User.objects.filter(username=email).exists():
            return JsonResponse(status=400, data={'error': 'This email address already registered'})

        uu = User.objects.create(first_name=name_, email=email, username=email)
        uu.set_password(password)
        uu.save()
        try:
            service_instances = Myservice.objects.filter(is_permisstion=True) 
            for service_instance in service_instances:
                Mypermission.objects.create(user=uu, service=service_instance ,is_check=True)
        except:
            pass

      
       
        return JsonResponse(status=200, data={})

    response = render(request, 'superadmin/auth/register.html')
    return response


@login_required
def logout_page(request):
   
    response = redirect('/login')  # Redirect to the desired page after logout
    
    # Set cookies to expire in the past
    response.delete_cookie('name')
    response.delete_cookie('email')
    response.delete_cookie('sessionid')
    response.delete_cookie('csrftoken')
    logout(request)
    # Add more delete_cookie() calls for each cookie you want to remove
    
    return response
    #return redirect('/login')
@api_view(['GET'])
def forget_password(request):
    return render(request, 'superadmin/auth/forgetpassword.html')


class Util:
    @staticmethod
    def send_email(data):
        email = EmailMessage(
            subject=data['subject'],
            body=data['body'],
            from_email="example.com", #os.environ.get('EMAIL_FROM'),
            to=[data['to_email']]
        );
        email.send()


@api_view(['POST'])
def forget_password_send_email(request):
    email = request.POST['email'].lower().strip()

    # if User.objects.filter(username=email).exists():
    #     user=User.objects.filter(username=email).last()
    #     subject = "Password Reset Requested"

    #     return render(request, 'superadmin/auth/reset_password.html',context={'username': email})
    if User.objects.filter(email=email).exists():

        user = User.objects.get(email=email)
        uid = urlsafe_b64encode(force_bytes(user.id))
        # print('Encoded UID', uid)
        # token = PasswordResetTokenGenerator().make_token(user)
        # print('Password Reset Token', token)
        link = 'http://127.0.0.1:8000/forget_password_send_email_check/' + uid + '/'
        print('Password Reset Link', link)
        # Send EMail
        body = 'Click Following Link to Reset Your Password ' + link
        data = {
            'subject': 'Reset Your Password',
            'body': body,
            'to_email': 'manzoorhussain075@gmail.com'
        }
        Util.send_email(data)
        return render(request, 'superadmin/auth/reset_password.html', context={'username': "done"})
    else:
        return render(request, 'superadmin/auth/forgetpassword.html',
                      context={'error': "Your Account Does not Exist pleas"})


@api_view(['GET'])
def forget_password_send_email_check(request, uid):
    id = urlsafe_b64decode(uid)

    user = User.objects.filter(id=id).last()
    username = user.username
    return render(request, 'superadmin/auth/reset_password.html', context={'username': username})


@api_view(['POST'])
def update_password(request):
    new_password = request.POST['password1']
    confirm_password = request.POST['password2']
    email = request.POST['username']

    if new_password != confirm_password:
        return Response(status=400, data={'error': 'Both passwords must match'})

    user = User.objects.filter(username=email).last()
    user.set_password(new_password)
    user.save()
    login(request, user)
    return redirect("login")
@api_view(['POST'])
@login_required
def delete_service(request):
    Myservice.objects.filter(id=request.data['id']).delete()
    return Response(status=200)


@api_view(['POST'])
@login_required
def change_service(request):
    dm_ = Myservice.objects.get(id=request.POST['id'])
    is_permission_ = True
    if dm_.is_permisstion:
        is_permission_ = False
    dm_.is_permisstion = is_permission_
    dm_.save()
    return Response(status=200)


@api_view(['GET'])
@login_required
def get_service_detail(request):
    service_ = Myservice.objects.get(id=request.GET.get('id'))
    data_ = ServiceSerializer(service_)
    data_ = data_.data
    return Response(status=200, data=data_)


@api_view(['POST'])
@login_required
def add_service(request):
    id_ = request.GET.get('id', None)
    title_ = request.POST['title']
    is_permisstion = request.POST.getlist('is_permisstion')
    description = request.POST['description']

    print("description",is_permisstion)
    is_permisstion = ','.join(is_permisstion)
    if not is_permisstion:
        is_permisstion = 'True'
        
   
  
    if not id_:
        Myservice.objects.create(title=title_, is_permisstion=is_permisstion, description=description)
        return Response(status=200)

    dd = Myservice.objects.get(id=id_)
    dd.description = description
    dd.title = title_
    dd.is_permisstion = is_permisstion
    dd.save()
    return Response(status=200)

@api_view(['GET'])
@login_required
def get_user_detail(request):
    service = Myservice.objects.all()
    permission = Mypermission.objects.all()
    users = User.objects.filter(is_superuser=False).exclude(username="hussain")
    return render(request, 'superadmin/user_permission.html', context ={"permission":permission,"users":users,"service":service})

@api_view(['GET'])
@login_required
def get_user_services(request):
    username_ = request.GET.get('username', None)
    user= User.objects.filter(username=username_).last()
    mypermissions = Mypermission.objects.filter(user=user)
    myservices = Myservice.objects.filter(mypermission__user=user)
    json_data = serializers.serialize('json', myservices)   
    return Response(status=200, data=json_data)

@api_view(['POST'])
@login_required
def change_permission(request):
    service_ = Myservice.objects.get(id=request.POST['service'])
    user_ = User.objects.get(username=request.POST['username'])
    ischeck_ = request.POST['ischeck']
    if ischeck_ == 'true':
        permission = Mypermission.objects.create(user=user_, service=service_, is_check=True)
       
    else:
        permission = Mypermission.objects.filter(user=user_, service=service_ , is_check=True)
        permission.delete()

    return Response(status=200)

    

pdf/superadmin/templates/superadmin/layout/base.html
{% load static %}
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="images/favicon.ico" type="image/ico"/>

    <title>Resume Formatter</title>

    <!-- Bootstrap -->
    <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">
    <!-- iCheck -->
    <link href="{% static 'vendors/iCheck/skins/flat/green.css' %}" rel="stylesheet">

    <!-- bootstrap-progressbar -->
    <link href="{% static 'vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet">
    <!-- JQVMap -->
    <link href="{% static 'vendors/jqvmap/dist/jqvmap.min.css' %}" rel="stylesheet"/>
    <!-- bootstrap-daterangepicker -->
    <link href="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.css' %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">

    <link href="{% static 'vendors/pnotify/dist/pnotify.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/pnotify/dist/pnotify.buttons.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/pnotify/dist/pnotify.nonblock.css' %}" rel="stylesheet">

    <!-- jQuery custom content scroller -->
    <link href="{% static 'vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css' %}"
          rel="stylesheet"/>

    <!-- Animate.css -->
    <link href="{% static 'vendors/switchery/dist/switchery.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/animate.css/animate.min.css' %}" rel="stylesheet">
    <!-- starrr -->
    <link href="{% static 'vendors/starrr/dist/starrr.css' %}" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">
    <link href="{% static 'custom_css/custom.css' %}" rel="stylesheet">


    <style>

        .img_height_width_header {
            width: 30% !important;
            height: 60% !important;
        }
        body{
            background:#fff;
        }
        .upload_button{

            color: #fff;
            background-color: #dc3545;
            border-color: #dc3545;
            padding: 12PX 96PX;
          }
        {% block style %} {% endblock %}

    </style>


</head>

<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href="{% url 'superadmin:dashboard' %}" class="site_title">
                           
                            <span>Resume Formatter</span></a>
                    </div>
    
                    <div class="clearfix"></div>
    
                    <br/>
    
                    <!-- sidebar menu -->
                    {% include "superadmin/layout/sidebar.html" %}
                    <!-- /sidebar menu -->
    
                </div>
            </div>
    
            <!-- top navigation -->
            {% include "superadmin/layout/header.html" %}
            <!-- /top navigation -->
    
            <!-- page content -->
            {% block content %}{% endblock %}
            <!-- /page content -->
    
            <!-- footer content -->
            {% include "superadmin/layout/footer.html" %}
            <!-- /footer content -->
        </div>
    </div>

<!-- jQuery -->
<script src="{% static 'vendors/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap -->
<script src="{% static 'vendors/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'vendors/fastclick/lib/fastclick.js' %}"></script>
<!-- NProgress -->
<script src="{% static 'vendors/nprogress/nprogress.js' %}"></script>
<!-- Chart.js -->
<script src="{% static 'vendors/Chart.js/dist/Chart.min.js' %}"></script>
<!-- gauge.js -->
<script src="{% static 'vendors/gauge.js/dist/gauge.min.js' %}"></script>
<!-- bootstrap-progressbar -->
<script src="{% static 'vendors/bootstrap-progressbar/bootstrap-progressbar.min.js' %}"></script>
<!-- iCheck -->
<script src="{% static 'vendors/iCheck/icheck.min.js' %}"></script>
<!-- Skycons -->
<script src="{% static 'vendors/skycons/skycons.js' %}"></script>
<!-- Flot -->
<script src="{% static 'vendors/Flot/jquery.flot.js' %}"></script>
<script src="{% static 'vendors/Flot/jquery.flot.pie.js' %}"></script>
<script src="{% static 'vendors/Flot/jquery.flot.time.js' %}"></script>
<script src="{% static 'vendors/Flot/jquery.flot.stack.js' %}"></script>
<script src="{% static 'vendors/Flot/jquery.flot.resize.js' %}"></script>
<!-- Flot plugins -->
<script src="{% static 'vendors/flot.orderbars/js/jquery.flot.orderBars.js' %}"></script>
<script src="{% static 'vendors/flot-spline/js/jquery.flot.spline.min.js' %}"></script>
<script src="{% static 'vendors/flot.curvedlines/curvedLines.js' %}"></script>
<!-- DateJS -->
<script src="{% static 'vendors/DateJS/build/date.js' %}"></script>
<!-- JQVMap -->
<script src="{% static 'vendors/jqvmap/dist/jquery.vmap.js' %}"></script>
<script src="{% static 'vendors/jqvmap/dist/maps/jquery.vmap.world.js' %}"></script>
<script src="{% static 'vendors/jqvmap/examples/js/jquery.vmap.sampledata.js' %}"></script>
<!-- bootstrap-daterangepicker -->
<script src="{% static 'vendors/moment/min/moment.min.js' %}"></script>
<script src="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
<script src="{% static 'vendors/switchery/dist/switchery.min.js' %}"></script>


<script src="{% static 'vendors/pnotify/dist/pnotify.js' %}"></script>
<script src="{% static 'vendors/pnotify/dist/pnotify.buttons.js' %}"></script>
<script src="{% static 'vendors/pnotify/dist/pnotify.nonblock.js' %}"></script>
<!-- Custom Theme Scripts -->
<script src="{% static 'build/js/custom.min.js' %}"></script>
<script src="{% static 'js/custom_functions.js' %}"></script>


<script type="text/javascript">

    function changeStatusOfUserTrade() {
        debugger
        if ($("#Trade_cnt").is(':checked')) {
            var switchStatus = $("#Trade_cnt").is(':checked');
            $("#Trade_cnt").prop('checked', false);
            $(this).prop('checked', false);
        } else {
            var switchStatus = $("#Trade_cnt").is(':checked');
            $("#Trade_cnt").prop('checked', true);
            $(this).prop('checked', true);
        }

        var fd = new FormData();
        $.ajax({
            url: "/core/change_trade_status/",
            headers: {"X-CSRFToken": '{{csrf_token}}'},
            data: fd,
            cache: false,
            processData: false,
            contentType: false,
            type: 'POST',
            success: function (dataofconfirm) {
                ShowNotify('Congratulation', 'Trade status updated', 'success');
                window.location.reload()
            }

        });

    }

</script>

{% block javascript %}
{% endblock %}

</body>
</html>

pdf/superadmin/templates/superadmin/layout/footer.html
<footer>
          <div class="pull-right">
            All Rights Reserved By Machine learning 1
          </div>
          <div class="clearfix"></div>
        </footer>

pdf/superadmin/templates/superadmin/layout/header.html
<div class="top_nav">
    <div class="nav_menu">

      
        <div class="nav toggle">
            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
        </div>

       


        <nav class="nav navbar-nav" style="display: inline">
            <ul class=" navbar-right">
                <li class="nav-item dropdown open" style="padding-left: 15px;">
                    <a href="javascript:;" class="user-profile dropdown-toggle" aria-haspopup="true" id="navbarDropdown"
                       data-toggle="dropdown" aria-expanded="false">
                        {% if request.user.userprofile %}
                            {% if request.user.userprofile.image %}
                                <img src="{{ request.user.userprofile.image.url }}" alt="">
                            {% else %}
                                <img src="/static/wheel.gif" alt="">
                            {% endif %}
                        {% else %}
                            <img src="/static/wheel.gif" alt="">
                        {% endif %}
                        {{ request.user.first_name }}
                    </a>
                    <div class="dropdown-menu dropdown-usermenu pull-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href=""> Profile</a>

                        <a class="dropdown-item" href="{% url 'logout' %}"><i class="fa fa-sign-out pull-right"></i> Log
                            Out</a>
                    </div>
                </li>
                {##}
                {#                <li role="presentation" class="nav-item dropdown open">#}
                {#                  <a href="javascript:;" class="dropdown-toggle info-number" id="navbarDropdown1" data-toggle="dropdown" aria-expanded="false">#}
                {#                    <i class="fa fa-envelope-o"></i>#}
                {#                    <span class="badge bg-green">6</span>#}
                {#                  </a>#}
                {#                  <ul class="dropdown-menu list-unstyled msg_list" role="menu" aria-labelledby="navbarDropdown1">#}
                {#                    <li class="nav-item">#}
                {#                      <a class="dropdown-item">#}
                {#                        <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>#}
                {#                        <span>#}
                {#                          <span>John Smith</span>#}
                {#                          <span class="time">3 mins ago</span>#}
                {#                        </span>#}
                {#                        <span class="message">#}
                {#                          Film festivals used to be do-or-die moments for movie makers. They were where...#}
                {#                        </span>#}
                {#                      </a>#}
                {#                    </li>#}
                {#                  </ul>#}
                {#                </li>#}
            </ul>
        </nav>
    </div>
</div>

pdf/superadmin/templates/superadmin/layout/sidebar.html
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
        <ul class="nav side-menu">
            <li><a href="{% url 'superadmin:dashboard' %}"><i class="fa fa-home"></i> Home</a></li>
          
            <li><a href="{% url 'superadmin:get_user_detail' %}"><i class="fa fa-user"></i> User</a></li>           

        </ul>
    </div>

</div>